source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LvModelWindow_Example', :exclusive => true do
  pod "LvModelWindow", :path => "../"
end

target 'LvModelWindow_Tests', :exclusive => true do
  pod "LvModelWindow", :path => "../"

  
end
