source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LvModelWindow_Example' do
  pod "LvModelWindow", :path => "../"
end

target 'LvModelWindow_Tests' do
  pod "LvModelWindow", :path => "../"

  
end
